name: Daily build and release

on:
  schedule:
    # 04:30 AM (KST) Mon-Fri
    - cron: "30 19 * * 0-4"

  workflow_dispatch:

jobs:
  generate_doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install packages
      run: |
        sudo apt-get install python3-dev libxml2-dev libxslt1-dev cmake libyaml-dev libclang-dev llvm-dev libglib2.0-dev libjson-glib-dev flex
        python -m pip install --upgrade pip
        pip install hotdoc
    - name: Generate doc using hotdoc
      uses: ./Documentation/hotdoc/gen-hotdoc.sh
